// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: extension.proto

package extpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty is a placeholder for RPCs with no meaningful request/response.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_extension_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{0}
}

type InitializeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ExtensionId     string                 `protobuf:"bytes,2,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	ExtensionDir    string                 `protobuf:"bytes,3,opt,name=extension_dir,json=extensionDir,proto3" json:"extension_dir,omitempty"`
	State           *structpb.Struct       `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	// host_address is the gRPC address of the HostService server.
	// Extensions can dial this address to call SetState/Log on the host.
	HostAddress   string `protobuf:"bytes,5,opt,name=host_address,json=hostAddress,proto3" json:"host_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_extension_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{1}
}

func (x *InitializeRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *InitializeRequest) GetExtensionId() string {
	if x != nil {
		return x.ExtensionId
	}
	return ""
}

func (x *InitializeRequest) GetExtensionDir() string {
	if x != nil {
		return x.ExtensionDir
	}
	return ""
}

func (x *InitializeRequest) GetState() *structpb.Struct {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *InitializeRequest) GetHostAddress() string {
	if x != nil {
		return x.HostAddress
	}
	return ""
}

type InitializeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Hooks           []string               `protobuf:"bytes,2,rep,name=hooks,proto3" json:"hooks,omitempty"`
	Tools           []*ToolDefinition      `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_extension_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{2}
}

func (x *InitializeResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *InitializeResponse) GetHooks() []string {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *InitializeResponse) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ToolDefinition struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Label       string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// JSON Schema for the tool's parameters, encoded as a Struct.
	Parameters    *structpb.Struct `protobuf:"bytes,4,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_extension_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{3}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ToolCallHookEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId    string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Input         *structpb.Struct       `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallHookEvent) Reset() {
	*x = ToolCallHookEvent{}
	mi := &file_extension_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallHookEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallHookEvent) ProtoMessage() {}

func (x *ToolCallHookEvent) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallHookEvent.ProtoReflect.Descriptor instead.
func (*ToolCallHookEvent) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{4}
}

func (x *ToolCallHookEvent) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolCallHookEvent) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCallHookEvent) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

type ToolCallHookResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         bool                   `protobuf:"varint,1,opt,name=block,proto3" json:"block,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallHookResult) Reset() {
	*x = ToolCallHookResult{}
	mi := &file_extension_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallHookResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallHookResult) ProtoMessage() {}

func (x *ToolCallHookResult) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallHookResult.ProtoReflect.Descriptor instead.
func (*ToolCallHookResult) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{5}
}

func (x *ToolCallHookResult) GetBlock() bool {
	if x != nil {
		return x.Block
	}
	return false
}

func (x *ToolCallHookResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ToolResultHookEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId    string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Input         *structpb.Struct       `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	Content       []*ContentBlock        `protobuf:"bytes,4,rep,name=content,proto3" json:"content,omitempty"`
	IsError       bool                   `protobuf:"varint,5,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResultHookEvent) Reset() {
	*x = ToolResultHookEvent{}
	mi := &file_extension_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultHookEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultHookEvent) ProtoMessage() {}

func (x *ToolResultHookEvent) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResultHookEvent.ProtoReflect.Descriptor instead.
func (*ToolResultHookEvent) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{6}
}

func (x *ToolResultHookEvent) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolResultHookEvent) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolResultHookEvent) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ToolResultHookEvent) GetContent() []*ContentBlock {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ToolResultHookEvent) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type ToolResultHookResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []*ContentBlock        `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
	IsError       *bool                  `protobuf:"varint,2,opt,name=is_error,json=isError,proto3,oneof" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResultHookResult) Reset() {
	*x = ToolResultHookResult{}
	mi := &file_extension_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultHookResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultHookResult) ProtoMessage() {}

func (x *ToolResultHookResult) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResultHookResult.ProtoReflect.Descriptor instead.
func (*ToolResultHookResult) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{7}
}

func (x *ToolResultHookResult) GetContent() []*ContentBlock {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ToolResultHookResult) GetIsError() bool {
	if x != nil && x.IsError != nil {
		return *x.IsError
	}
	return false
}

type ContextHookEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Messages are JSON-encoded AgentMessages.
	// We use bytes to preserve the exact serialization format.
	Messages      [][]byte `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextHookEvent) Reset() {
	*x = ContextHookEvent{}
	mi := &file_extension_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextHookEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextHookEvent) ProtoMessage() {}

func (x *ContextHookEvent) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextHookEvent.ProtoReflect.Descriptor instead.
func (*ContextHookEvent) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{8}
}

func (x *ContextHookEvent) GetMessages() [][]byte {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ContextHookResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      [][]byte               `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextHookResult) Reset() {
	*x = ContextHookResult{}
	mi := &file_extension_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextHookResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextHookResult) ProtoMessage() {}

func (x *ContextHookResult) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextHookResult.ProtoReflect.Descriptor instead.
func (*ContextHookResult) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{9}
}

func (x *ContextHookResult) GetMessages() [][]byte {
	if x != nil {
		return x.Messages
	}
	return nil
}

type BeforeAgentStartHookEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemPrompt  string                 `protobuf:"bytes,1,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeforeAgentStartHookEvent) Reset() {
	*x = BeforeAgentStartHookEvent{}
	mi := &file_extension_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeforeAgentStartHookEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeforeAgentStartHookEvent) ProtoMessage() {}

func (x *BeforeAgentStartHookEvent) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeforeAgentStartHookEvent.ProtoReflect.Descriptor instead.
func (*BeforeAgentStartHookEvent) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{10}
}

func (x *BeforeAgentStartHookEvent) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

type BeforeAgentStartHookResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemPrompt  string                 `protobuf:"bytes,1,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeforeAgentStartHookResult) Reset() {
	*x = BeforeAgentStartHookResult{}
	mi := &file_extension_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeforeAgentStartHookResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeforeAgentStartHookResult) ProtoMessage() {}

func (x *BeforeAgentStartHookResult) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeforeAgentStartHookResult.ProtoReflect.Descriptor instead.
func (*BeforeAgentStartHookResult) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{11}
}

func (x *BeforeAgentStartHookResult) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

type AgentEndEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      [][]byte               `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEndEvent) Reset() {
	*x = AgentEndEvent{}
	mi := &file_extension_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEndEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEndEvent) ProtoMessage() {}

func (x *AgentEndEvent) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEndEvent.ProtoReflect.Descriptor instead.
func (*AgentEndEvent) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{12}
}

func (x *AgentEndEvent) GetMessages() [][]byte {
	if x != nil {
		return x.Messages
	}
	return nil
}

type TurnEndEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TurnMessage   []byte                 `protobuf:"bytes,1,opt,name=turn_message,json=turnMessage,proto3" json:"turn_message,omitempty"`
	ToolResults   [][]byte               `protobuf:"bytes,2,rep,name=tool_results,json=toolResults,proto3" json:"tool_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnEndEvent) Reset() {
	*x = TurnEndEvent{}
	mi := &file_extension_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnEndEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnEndEvent) ProtoMessage() {}

func (x *TurnEndEvent) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnEndEvent.ProtoReflect.Descriptor instead.
func (*TurnEndEvent) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{13}
}

func (x *TurnEndEvent) GetTurnMessage() []byte {
	if x != nil {
		return x.TurnMessage
	}
	return nil
}

func (x *TurnEndEvent) GetToolResults() [][]byte {
	if x != nil {
		return x.ToolResults
	}
	return nil
}

type ContentBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Block:
	//
	//	*ContentBlock_Text
	//	*ContentBlock_Image
	Block         isContentBlock_Block `protobuf_oneof:"block"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBlock) Reset() {
	*x = ContentBlock{}
	mi := &file_extension_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBlock) ProtoMessage() {}

func (x *ContentBlock) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentBlock.ProtoReflect.Descriptor instead.
func (*ContentBlock) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{14}
}

func (x *ContentBlock) GetBlock() isContentBlock_Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *ContentBlock) GetText() *TextContent {
	if x != nil {
		if x, ok := x.Block.(*ContentBlock_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *ContentBlock) GetImage() *ImageContent {
	if x != nil {
		if x, ok := x.Block.(*ContentBlock_Image); ok {
			return x.Image
		}
	}
	return nil
}

type isContentBlock_Block interface {
	isContentBlock_Block()
}

type ContentBlock_Text struct {
	Text *TextContent `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type ContentBlock_Image struct {
	Image *ImageContent `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

func (*ContentBlock_Text) isContentBlock_Block() {}

func (*ContentBlock_Image) isContentBlock_Block() {}

type TextContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextContent) Reset() {
	*x = TextContent{}
	mi := &file_extension_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextContent) ProtoMessage() {}

func (x *TextContent) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextContent.ProtoReflect.Descriptor instead.
func (*TextContent) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{15}
}

func (x *TextContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ImageContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageContent) Reset() {
	*x = ImageContent{}
	mi := &file_extension_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageContent) ProtoMessage() {}

func (x *ImageContent) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageContent.ProtoReflect.Descriptor instead.
func (*ImageContent) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{16}
}

func (x *ImageContent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ImageContent) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type ToolExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId    string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Params        *structpb.Struct       `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolExecuteRequest) Reset() {
	*x = ToolExecuteRequest{}
	mi := &file_extension_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecuteRequest) ProtoMessage() {}

func (x *ToolExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolExecuteRequest.ProtoReflect.Descriptor instead.
func (*ToolExecuteRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{17}
}

func (x *ToolExecuteRequest) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolExecuteRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolExecuteRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

type ToolExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, this is a progress update (not the final result).
	IsProgress    bool             `protobuf:"varint,1,opt,name=is_progress,json=isProgress,proto3" json:"is_progress,omitempty"`
	Content       []*ContentBlock  `protobuf:"bytes,2,rep,name=content,proto3" json:"content,omitempty"`
	Details       *structpb.Struct `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	IsError       bool             `protobuf:"varint,4,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolExecuteResponse) Reset() {
	*x = ToolExecuteResponse{}
	mi := &file_extension_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecuteResponse) ProtoMessage() {}

func (x *ToolExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolExecuteResponse.ProtoReflect.Descriptor instead.
func (*ToolExecuteResponse) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{18}
}

func (x *ToolExecuteResponse) GetIsProgress() bool {
	if x != nil {
		return x.IsProgress
	}
	return false
}

func (x *ToolExecuteResponse) GetContent() []*ContentBlock {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ToolExecuteResponse) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ToolExecuteResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type StateSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSetRequest) Reset() {
	*x = StateSetRequest{}
	mi := &file_extension_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSetRequest) ProtoMessage() {}

func (x *StateSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSetRequest.ProtoReflect.Descriptor instead.
func (*StateSetRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{19}
}

func (x *StateSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StateSetRequest) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"` // "debug", "info", "warn", "error"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Fields        *structpb.Struct       `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_extension_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{20}
}

func (x *LogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRequest) GetFields() *structpb.Struct {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_extension_proto protoreflect.FileDescriptor

const file_extension_proto_rawDesc = "" +
	"\n" +
	"\x0fextension.proto\x12\x0fpi.agent.ext.v1\x1a\x1cgoogle/protobuf/struct.proto\"\a\n" +
	"\x05Empty\"\xd8\x01\n" +
	"\x11InitializeRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12!\n" +
	"\fextension_id\x18\x02 \x01(\tR\vextensionId\x12#\n" +
	"\rextension_dir\x18\x03 \x01(\tR\fextensionDir\x12-\n" +
	"\x05state\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x05state\x12!\n" +
	"\fhost_address\x18\x05 \x01(\tR\vhostAddress\"\x8c\x01\n" +
	"\x12InitializeResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x14\n" +
	"\x05hooks\x18\x02 \x03(\tR\x05hooks\x125\n" +
	"\x05tools\x18\x03 \x03(\v2\x1f.pi.agent.ext.v1.ToolDefinitionR\x05tools\"\x95\x01\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x127\n" +
	"\n" +
	"parameters\x18\x04 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\"\x81\x01\n" +
	"\x11ToolCallHookEvent\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12-\n" +
	"\x05input\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x05input\"B\n" +
	"\x12ToolCallHookResult\x12\x14\n" +
	"\x05block\x18\x01 \x01(\bR\x05block\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xd7\x01\n" +
	"\x13ToolResultHookEvent\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12-\n" +
	"\x05input\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x05input\x127\n" +
	"\acontent\x18\x04 \x03(\v2\x1d.pi.agent.ext.v1.ContentBlockR\acontent\x12\x19\n" +
	"\bis_error\x18\x05 \x01(\bR\aisError\"|\n" +
	"\x14ToolResultHookResult\x127\n" +
	"\acontent\x18\x01 \x03(\v2\x1d.pi.agent.ext.v1.ContentBlockR\acontent\x12\x1e\n" +
	"\bis_error\x18\x02 \x01(\bH\x00R\aisError\x88\x01\x01B\v\n" +
	"\t_is_error\".\n" +
	"\x10ContextHookEvent\x12\x1a\n" +
	"\bmessages\x18\x01 \x03(\fR\bmessages\"/\n" +
	"\x11ContextHookResult\x12\x1a\n" +
	"\bmessages\x18\x01 \x03(\fR\bmessages\"@\n" +
	"\x19BeforeAgentStartHookEvent\x12#\n" +
	"\rsystem_prompt\x18\x01 \x01(\tR\fsystemPrompt\"A\n" +
	"\x1aBeforeAgentStartHookResult\x12#\n" +
	"\rsystem_prompt\x18\x01 \x01(\tR\fsystemPrompt\"+\n" +
	"\rAgentEndEvent\x12\x1a\n" +
	"\bmessages\x18\x01 \x03(\fR\bmessages\"T\n" +
	"\fTurnEndEvent\x12!\n" +
	"\fturn_message\x18\x01 \x01(\fR\vturnMessage\x12!\n" +
	"\ftool_results\x18\x02 \x03(\fR\vtoolResults\"\x82\x01\n" +
	"\fContentBlock\x122\n" +
	"\x04text\x18\x01 \x01(\v2\x1c.pi.agent.ext.v1.TextContentH\x00R\x04text\x125\n" +
	"\x05image\x18\x02 \x01(\v2\x1d.pi.agent.ext.v1.ImageContentH\x00R\x05imageB\a\n" +
	"\x05block\"!\n" +
	"\vTextContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"?\n" +
	"\fImageContent\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\"\x84\x01\n" +
	"\x12ToolExecuteRequest\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12/\n" +
	"\x06params\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06params\"\xbd\x01\n" +
	"\x13ToolExecuteResponse\x12\x1f\n" +
	"\vis_progress\x18\x01 \x01(\bR\n" +
	"isProgress\x127\n" +
	"\acontent\x18\x02 \x03(\v2\x1d.pi.agent.ext.v1.ContentBlockR\acontent\x121\n" +
	"\adetails\x18\x03 \x01(\v2\x17.google.protobuf.StructR\adetails\x12\x19\n" +
	"\bis_error\x18\x04 \x01(\bR\aisError\"Q\n" +
	"\x0fStateSetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value\"m\n" +
	"\n" +
	"LogRequest\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x06fields\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06fields2\x88\b\n" +
	"\x10ExtensionService\x12U\n" +
	"\n" +
	"Initialize\x12\".pi.agent.ext.v1.InitializeRequest\x1a#.pi.agent.ext.v1.InitializeResponse\x12:\n" +
	"\bShutdown\x12\x16.pi.agent.ext.v1.Empty\x1a\x16.pi.agent.ext.v1.Empty\x12U\n" +
	"\n" +
	"OnToolCall\x12\".pi.agent.ext.v1.ToolCallHookEvent\x1a#.pi.agent.ext.v1.ToolCallHookResult\x12[\n" +
	"\fOnToolResult\x12$.pi.agent.ext.v1.ToolResultHookEvent\x1a%.pi.agent.ext.v1.ToolResultHookResult\x12R\n" +
	"\tOnContext\x12!.pi.agent.ext.v1.ContextHookEvent\x1a\".pi.agent.ext.v1.ContextHookResult\x12m\n" +
	"\x12OnBeforeAgentStart\x12*.pi.agent.ext.v1.BeforeAgentStartHookEvent\x1a+.pi.agent.ext.v1.BeforeAgentStartHookResult\x12>\n" +
	"\fOnAgentStart\x12\x16.pi.agent.ext.v1.Empty\x1a\x16.pi.agent.ext.v1.Empty\x12D\n" +
	"\n" +
	"OnAgentEnd\x12\x1e.pi.agent.ext.v1.AgentEndEvent\x1a\x16.pi.agent.ext.v1.Empty\x12=\n" +
	"\vOnTurnStart\x12\x16.pi.agent.ext.v1.Empty\x1a\x16.pi.agent.ext.v1.Empty\x12B\n" +
	"\tOnTurnEnd\x12\x1d.pi.agent.ext.v1.TurnEndEvent\x1a\x16.pi.agent.ext.v1.Empty\x12@\n" +
	"\x0eOnSessionStart\x12\x16.pi.agent.ext.v1.Empty\x1a\x16.pi.agent.ext.v1.Empty\x12C\n" +
	"\x11OnSessionShutdown\x12\x16.pi.agent.ext.v1.Empty\x1a\x16.pi.agent.ext.v1.Empty\x12Z\n" +
	"\vExecuteTool\x12#.pi.agent.ext.v1.ToolExecuteRequest\x1a$.pi.agent.ext.v1.ToolExecuteResponse0\x012\x8f\x01\n" +
	"\vHostService\x12D\n" +
	"\bSetState\x12 .pi.agent.ext.v1.StateSetRequest\x1a\x16.pi.agent.ext.v1.Empty\x12:\n" +
	"\x03Log\x12\x1b.pi.agent.ext.v1.LogRequest\x1a\x16.pi.agent.ext.v1.EmptyB9Z7github.com/nickolaev/pi-mono/packages/go-pi-agent/extpbb\x06proto3"

var (
	file_extension_proto_rawDescOnce sync.Once
	file_extension_proto_rawDescData []byte
)

func file_extension_proto_rawDescGZIP() []byte {
	file_extension_proto_rawDescOnce.Do(func() {
		file_extension_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extension_proto_rawDesc), len(file_extension_proto_rawDesc)))
	})
	return file_extension_proto_rawDescData
}

var file_extension_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_extension_proto_goTypes = []any{
	(*Empty)(nil),                      // 0: pi.agent.ext.v1.Empty
	(*InitializeRequest)(nil),          // 1: pi.agent.ext.v1.InitializeRequest
	(*InitializeResponse)(nil),         // 2: pi.agent.ext.v1.InitializeResponse
	(*ToolDefinition)(nil),             // 3: pi.agent.ext.v1.ToolDefinition
	(*ToolCallHookEvent)(nil),          // 4: pi.agent.ext.v1.ToolCallHookEvent
	(*ToolCallHookResult)(nil),         // 5: pi.agent.ext.v1.ToolCallHookResult
	(*ToolResultHookEvent)(nil),        // 6: pi.agent.ext.v1.ToolResultHookEvent
	(*ToolResultHookResult)(nil),       // 7: pi.agent.ext.v1.ToolResultHookResult
	(*ContextHookEvent)(nil),           // 8: pi.agent.ext.v1.ContextHookEvent
	(*ContextHookResult)(nil),          // 9: pi.agent.ext.v1.ContextHookResult
	(*BeforeAgentStartHookEvent)(nil),  // 10: pi.agent.ext.v1.BeforeAgentStartHookEvent
	(*BeforeAgentStartHookResult)(nil), // 11: pi.agent.ext.v1.BeforeAgentStartHookResult
	(*AgentEndEvent)(nil),              // 12: pi.agent.ext.v1.AgentEndEvent
	(*TurnEndEvent)(nil),               // 13: pi.agent.ext.v1.TurnEndEvent
	(*ContentBlock)(nil),               // 14: pi.agent.ext.v1.ContentBlock
	(*TextContent)(nil),                // 15: pi.agent.ext.v1.TextContent
	(*ImageContent)(nil),               // 16: pi.agent.ext.v1.ImageContent
	(*ToolExecuteRequest)(nil),         // 17: pi.agent.ext.v1.ToolExecuteRequest
	(*ToolExecuteResponse)(nil),        // 18: pi.agent.ext.v1.ToolExecuteResponse
	(*StateSetRequest)(nil),            // 19: pi.agent.ext.v1.StateSetRequest
	(*LogRequest)(nil),                 // 20: pi.agent.ext.v1.LogRequest
	(*structpb.Struct)(nil),            // 21: google.protobuf.Struct
	(*structpb.Value)(nil),             // 22: google.protobuf.Value
}
var file_extension_proto_depIdxs = []int32{
	21, // 0: pi.agent.ext.v1.InitializeRequest.state:type_name -> google.protobuf.Struct
	3,  // 1: pi.agent.ext.v1.InitializeResponse.tools:type_name -> pi.agent.ext.v1.ToolDefinition
	21, // 2: pi.agent.ext.v1.ToolDefinition.parameters:type_name -> google.protobuf.Struct
	21, // 3: pi.agent.ext.v1.ToolCallHookEvent.input:type_name -> google.protobuf.Struct
	21, // 4: pi.agent.ext.v1.ToolResultHookEvent.input:type_name -> google.protobuf.Struct
	14, // 5: pi.agent.ext.v1.ToolResultHookEvent.content:type_name -> pi.agent.ext.v1.ContentBlock
	14, // 6: pi.agent.ext.v1.ToolResultHookResult.content:type_name -> pi.agent.ext.v1.ContentBlock
	15, // 7: pi.agent.ext.v1.ContentBlock.text:type_name -> pi.agent.ext.v1.TextContent
	16, // 8: pi.agent.ext.v1.ContentBlock.image:type_name -> pi.agent.ext.v1.ImageContent
	21, // 9: pi.agent.ext.v1.ToolExecuteRequest.params:type_name -> google.protobuf.Struct
	14, // 10: pi.agent.ext.v1.ToolExecuteResponse.content:type_name -> pi.agent.ext.v1.ContentBlock
	21, // 11: pi.agent.ext.v1.ToolExecuteResponse.details:type_name -> google.protobuf.Struct
	22, // 12: pi.agent.ext.v1.StateSetRequest.value:type_name -> google.protobuf.Value
	21, // 13: pi.agent.ext.v1.LogRequest.fields:type_name -> google.protobuf.Struct
	1,  // 14: pi.agent.ext.v1.ExtensionService.Initialize:input_type -> pi.agent.ext.v1.InitializeRequest
	0,  // 15: pi.agent.ext.v1.ExtensionService.Shutdown:input_type -> pi.agent.ext.v1.Empty
	4,  // 16: pi.agent.ext.v1.ExtensionService.OnToolCall:input_type -> pi.agent.ext.v1.ToolCallHookEvent
	6,  // 17: pi.agent.ext.v1.ExtensionService.OnToolResult:input_type -> pi.agent.ext.v1.ToolResultHookEvent
	8,  // 18: pi.agent.ext.v1.ExtensionService.OnContext:input_type -> pi.agent.ext.v1.ContextHookEvent
	10, // 19: pi.agent.ext.v1.ExtensionService.OnBeforeAgentStart:input_type -> pi.agent.ext.v1.BeforeAgentStartHookEvent
	0,  // 20: pi.agent.ext.v1.ExtensionService.OnAgentStart:input_type -> pi.agent.ext.v1.Empty
	12, // 21: pi.agent.ext.v1.ExtensionService.OnAgentEnd:input_type -> pi.agent.ext.v1.AgentEndEvent
	0,  // 22: pi.agent.ext.v1.ExtensionService.OnTurnStart:input_type -> pi.agent.ext.v1.Empty
	13, // 23: pi.agent.ext.v1.ExtensionService.OnTurnEnd:input_type -> pi.agent.ext.v1.TurnEndEvent
	0,  // 24: pi.agent.ext.v1.ExtensionService.OnSessionStart:input_type -> pi.agent.ext.v1.Empty
	0,  // 25: pi.agent.ext.v1.ExtensionService.OnSessionShutdown:input_type -> pi.agent.ext.v1.Empty
	17, // 26: pi.agent.ext.v1.ExtensionService.ExecuteTool:input_type -> pi.agent.ext.v1.ToolExecuteRequest
	19, // 27: pi.agent.ext.v1.HostService.SetState:input_type -> pi.agent.ext.v1.StateSetRequest
	20, // 28: pi.agent.ext.v1.HostService.Log:input_type -> pi.agent.ext.v1.LogRequest
	2,  // 29: pi.agent.ext.v1.ExtensionService.Initialize:output_type -> pi.agent.ext.v1.InitializeResponse
	0,  // 30: pi.agent.ext.v1.ExtensionService.Shutdown:output_type -> pi.agent.ext.v1.Empty
	5,  // 31: pi.agent.ext.v1.ExtensionService.OnToolCall:output_type -> pi.agent.ext.v1.ToolCallHookResult
	7,  // 32: pi.agent.ext.v1.ExtensionService.OnToolResult:output_type -> pi.agent.ext.v1.ToolResultHookResult
	9,  // 33: pi.agent.ext.v1.ExtensionService.OnContext:output_type -> pi.agent.ext.v1.ContextHookResult
	11, // 34: pi.agent.ext.v1.ExtensionService.OnBeforeAgentStart:output_type -> pi.agent.ext.v1.BeforeAgentStartHookResult
	0,  // 35: pi.agent.ext.v1.ExtensionService.OnAgentStart:output_type -> pi.agent.ext.v1.Empty
	0,  // 36: pi.agent.ext.v1.ExtensionService.OnAgentEnd:output_type -> pi.agent.ext.v1.Empty
	0,  // 37: pi.agent.ext.v1.ExtensionService.OnTurnStart:output_type -> pi.agent.ext.v1.Empty
	0,  // 38: pi.agent.ext.v1.ExtensionService.OnTurnEnd:output_type -> pi.agent.ext.v1.Empty
	0,  // 39: pi.agent.ext.v1.ExtensionService.OnSessionStart:output_type -> pi.agent.ext.v1.Empty
	0,  // 40: pi.agent.ext.v1.ExtensionService.OnSessionShutdown:output_type -> pi.agent.ext.v1.Empty
	18, // 41: pi.agent.ext.v1.ExtensionService.ExecuteTool:output_type -> pi.agent.ext.v1.ToolExecuteResponse
	0,  // 42: pi.agent.ext.v1.HostService.SetState:output_type -> pi.agent.ext.v1.Empty
	0,  // 43: pi.agent.ext.v1.HostService.Log:output_type -> pi.agent.ext.v1.Empty
	29, // [29:44] is the sub-list for method output_type
	14, // [14:29] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_extension_proto_init() }
func file_extension_proto_init() {
	if File_extension_proto != nil {
		return
	}
	file_extension_proto_msgTypes[7].OneofWrappers = []any{}
	file_extension_proto_msgTypes[14].OneofWrappers = []any{
		(*ContentBlock_Text)(nil),
		(*ContentBlock_Image)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extension_proto_rawDesc), len(file_extension_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_extension_proto_goTypes,
		DependencyIndexes: file_extension_proto_depIdxs,
		MessageInfos:      file_extension_proto_msgTypes,
	}.Build()
	File_extension_proto = out.File
	file_extension_proto_goTypes = nil
	file_extension_proto_depIdxs = nil
}
