// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: extension.proto

package extpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExtensionService_Initialize_FullMethodName         = "/pi.agent.ext.v1.ExtensionService/Initialize"
	ExtensionService_Shutdown_FullMethodName           = "/pi.agent.ext.v1.ExtensionService/Shutdown"
	ExtensionService_OnToolCall_FullMethodName         = "/pi.agent.ext.v1.ExtensionService/OnToolCall"
	ExtensionService_OnToolResult_FullMethodName       = "/pi.agent.ext.v1.ExtensionService/OnToolResult"
	ExtensionService_OnContext_FullMethodName          = "/pi.agent.ext.v1.ExtensionService/OnContext"
	ExtensionService_OnBeforeAgentStart_FullMethodName = "/pi.agent.ext.v1.ExtensionService/OnBeforeAgentStart"
	ExtensionService_OnAgentStart_FullMethodName       = "/pi.agent.ext.v1.ExtensionService/OnAgentStart"
	ExtensionService_OnAgentEnd_FullMethodName         = "/pi.agent.ext.v1.ExtensionService/OnAgentEnd"
	ExtensionService_OnTurnStart_FullMethodName        = "/pi.agent.ext.v1.ExtensionService/OnTurnStart"
	ExtensionService_OnTurnEnd_FullMethodName          = "/pi.agent.ext.v1.ExtensionService/OnTurnEnd"
	ExtensionService_OnSessionStart_FullMethodName     = "/pi.agent.ext.v1.ExtensionService/OnSessionStart"
	ExtensionService_OnSessionShutdown_FullMethodName  = "/pi.agent.ext.v1.ExtensionService/OnSessionShutdown"
	ExtensionService_ExecuteTool_FullMethodName        = "/pi.agent.ext.v1.ExtensionService/ExecuteTool"
)

// ExtensionServiceClient is the client API for ExtensionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ExtensionService is implemented by extension subprocesses.
// The host launches the extension, connects via gRPC, and calls these RPCs
// to dispatch hooks and execute tools.
//
// Extension authors implement this interface. Use extpb.Serve() to start
// the gRPC server with the correct handshake protocol.
type ExtensionServiceClient interface {
	// Initialize performs the handshake. The extension declares which hooks
	// it subscribes to and which tools it provides.
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error)
	// Shutdown signals the extension to clean up and exit.
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// OnToolCall is invoked before a tool executes. Return block=true to prevent it.
	OnToolCall(ctx context.Context, in *ToolCallHookEvent, opts ...grpc.CallOption) (*ToolCallHookResult, error)
	// OnToolResult is invoked after a tool executes. Can modify the result.
	OnToolResult(ctx context.Context, in *ToolResultHookEvent, opts ...grpc.CallOption) (*ToolResultHookResult, error)
	// OnContext is invoked before sending messages to the LLM. Can modify messages.
	OnContext(ctx context.Context, in *ContextHookEvent, opts ...grpc.CallOption) (*ContextHookResult, error)
	// OnBeforeAgentStart is invoked before the agent loop begins. Can modify system prompt.
	OnBeforeAgentStart(ctx context.Context, in *BeforeAgentStartHookEvent, opts ...grpc.CallOption) (*BeforeAgentStartHookResult, error)
	OnAgentStart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	OnAgentEnd(ctx context.Context, in *AgentEndEvent, opts ...grpc.CallOption) (*Empty, error)
	OnTurnStart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	OnTurnEnd(ctx context.Context, in *TurnEndEvent, opts ...grpc.CallOption) (*Empty, error)
	OnSessionStart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	OnSessionShutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// ExecuteTool runs a tool registered by this extension.
	// Returns a stream: zero or more progress updates followed by a final result.
	ExecuteTool(ctx context.Context, in *ToolExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ToolExecuteResponse], error)
}

type extensionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExtensionServiceClient(cc grpc.ClientConnInterface) ExtensionServiceClient {
	return &extensionServiceClient{cc}
}

func (c *extensionServiceClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeResponse)
	err := c.cc.Invoke(ctx, ExtensionService_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ExtensionService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) OnToolCall(ctx context.Context, in *ToolCallHookEvent, opts ...grpc.CallOption) (*ToolCallHookResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolCallHookResult)
	err := c.cc.Invoke(ctx, ExtensionService_OnToolCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) OnToolResult(ctx context.Context, in *ToolResultHookEvent, opts ...grpc.CallOption) (*ToolResultHookResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolResultHookResult)
	err := c.cc.Invoke(ctx, ExtensionService_OnToolResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) OnContext(ctx context.Context, in *ContextHookEvent, opts ...grpc.CallOption) (*ContextHookResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextHookResult)
	err := c.cc.Invoke(ctx, ExtensionService_OnContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) OnBeforeAgentStart(ctx context.Context, in *BeforeAgentStartHookEvent, opts ...grpc.CallOption) (*BeforeAgentStartHookResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeforeAgentStartHookResult)
	err := c.cc.Invoke(ctx, ExtensionService_OnBeforeAgentStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) OnAgentStart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ExtensionService_OnAgentStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) OnAgentEnd(ctx context.Context, in *AgentEndEvent, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ExtensionService_OnAgentEnd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) OnTurnStart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ExtensionService_OnTurnStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) OnTurnEnd(ctx context.Context, in *TurnEndEvent, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ExtensionService_OnTurnEnd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) OnSessionStart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ExtensionService_OnSessionStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) OnSessionShutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ExtensionService_OnSessionShutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) ExecuteTool(ctx context.Context, in *ToolExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ToolExecuteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExtensionService_ServiceDesc.Streams[0], ExtensionService_ExecuteTool_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ToolExecuteRequest, ToolExecuteResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExtensionService_ExecuteToolClient = grpc.ServerStreamingClient[ToolExecuteResponse]

// ExtensionServiceServer is the server API for ExtensionService service.
// All implementations must embed UnimplementedExtensionServiceServer
// for forward compatibility.
//
// ExtensionService is implemented by extension subprocesses.
// The host launches the extension, connects via gRPC, and calls these RPCs
// to dispatch hooks and execute tools.
//
// Extension authors implement this interface. Use extpb.Serve() to start
// the gRPC server with the correct handshake protocol.
type ExtensionServiceServer interface {
	// Initialize performs the handshake. The extension declares which hooks
	// it subscribes to and which tools it provides.
	Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error)
	// Shutdown signals the extension to clean up and exit.
	Shutdown(context.Context, *Empty) (*Empty, error)
	// OnToolCall is invoked before a tool executes. Return block=true to prevent it.
	OnToolCall(context.Context, *ToolCallHookEvent) (*ToolCallHookResult, error)
	// OnToolResult is invoked after a tool executes. Can modify the result.
	OnToolResult(context.Context, *ToolResultHookEvent) (*ToolResultHookResult, error)
	// OnContext is invoked before sending messages to the LLM. Can modify messages.
	OnContext(context.Context, *ContextHookEvent) (*ContextHookResult, error)
	// OnBeforeAgentStart is invoked before the agent loop begins. Can modify system prompt.
	OnBeforeAgentStart(context.Context, *BeforeAgentStartHookEvent) (*BeforeAgentStartHookResult, error)
	OnAgentStart(context.Context, *Empty) (*Empty, error)
	OnAgentEnd(context.Context, *AgentEndEvent) (*Empty, error)
	OnTurnStart(context.Context, *Empty) (*Empty, error)
	OnTurnEnd(context.Context, *TurnEndEvent) (*Empty, error)
	OnSessionStart(context.Context, *Empty) (*Empty, error)
	OnSessionShutdown(context.Context, *Empty) (*Empty, error)
	// ExecuteTool runs a tool registered by this extension.
	// Returns a stream: zero or more progress updates followed by a final result.
	ExecuteTool(*ToolExecuteRequest, grpc.ServerStreamingServer[ToolExecuteResponse]) error
	mustEmbedUnimplementedExtensionServiceServer()
}

// UnimplementedExtensionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExtensionServiceServer struct{}

func (UnimplementedExtensionServiceServer) Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedExtensionServiceServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedExtensionServiceServer) OnToolCall(context.Context, *ToolCallHookEvent) (*ToolCallHookResult, error) {
	return nil, status.Error(codes.Unimplemented, "method OnToolCall not implemented")
}
func (UnimplementedExtensionServiceServer) OnToolResult(context.Context, *ToolResultHookEvent) (*ToolResultHookResult, error) {
	return nil, status.Error(codes.Unimplemented, "method OnToolResult not implemented")
}
func (UnimplementedExtensionServiceServer) OnContext(context.Context, *ContextHookEvent) (*ContextHookResult, error) {
	return nil, status.Error(codes.Unimplemented, "method OnContext not implemented")
}
func (UnimplementedExtensionServiceServer) OnBeforeAgentStart(context.Context, *BeforeAgentStartHookEvent) (*BeforeAgentStartHookResult, error) {
	return nil, status.Error(codes.Unimplemented, "method OnBeforeAgentStart not implemented")
}
func (UnimplementedExtensionServiceServer) OnAgentStart(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnAgentStart not implemented")
}
func (UnimplementedExtensionServiceServer) OnAgentEnd(context.Context, *AgentEndEvent) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnAgentEnd not implemented")
}
func (UnimplementedExtensionServiceServer) OnTurnStart(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnTurnStart not implemented")
}
func (UnimplementedExtensionServiceServer) OnTurnEnd(context.Context, *TurnEndEvent) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnTurnEnd not implemented")
}
func (UnimplementedExtensionServiceServer) OnSessionStart(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnSessionStart not implemented")
}
func (UnimplementedExtensionServiceServer) OnSessionShutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnSessionShutdown not implemented")
}
func (UnimplementedExtensionServiceServer) ExecuteTool(*ToolExecuteRequest, grpc.ServerStreamingServer[ToolExecuteResponse]) error {
	return status.Error(codes.Unimplemented, "method ExecuteTool not implemented")
}
func (UnimplementedExtensionServiceServer) mustEmbedUnimplementedExtensionServiceServer() {}
func (UnimplementedExtensionServiceServer) testEmbeddedByValue()                          {}

// UnsafeExtensionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtensionServiceServer will
// result in compilation errors.
type UnsafeExtensionServiceServer interface {
	mustEmbedUnimplementedExtensionServiceServer()
}

func RegisterExtensionServiceServer(s grpc.ServiceRegistrar, srv ExtensionServiceServer) {
	// If the following call panics, it indicates UnimplementedExtensionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExtensionService_ServiceDesc, srv)
}

func _ExtensionService_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_OnToolCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolCallHookEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).OnToolCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_OnToolCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).OnToolCall(ctx, req.(*ToolCallHookEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_OnToolResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolResultHookEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).OnToolResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_OnToolResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).OnToolResult(ctx, req.(*ToolResultHookEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_OnContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextHookEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).OnContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_OnContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).OnContext(ctx, req.(*ContextHookEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_OnBeforeAgentStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeforeAgentStartHookEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).OnBeforeAgentStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_OnBeforeAgentStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).OnBeforeAgentStart(ctx, req.(*BeforeAgentStartHookEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_OnAgentStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).OnAgentStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_OnAgentStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).OnAgentStart(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_OnAgentEnd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentEndEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).OnAgentEnd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_OnAgentEnd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).OnAgentEnd(ctx, req.(*AgentEndEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_OnTurnStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).OnTurnStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_OnTurnStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).OnTurnStart(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_OnTurnEnd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TurnEndEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).OnTurnEnd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_OnTurnEnd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).OnTurnEnd(ctx, req.(*TurnEndEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_OnSessionStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).OnSessionStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_OnSessionStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).OnSessionStart(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_OnSessionShutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).OnSessionShutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_OnSessionShutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).OnSessionShutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_ExecuteTool_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ToolExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExtensionServiceServer).ExecuteTool(m, &grpc.GenericServerStream[ToolExecuteRequest, ToolExecuteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExtensionService_ExecuteToolServer = grpc.ServerStreamingServer[ToolExecuteResponse]

// ExtensionService_ServiceDesc is the grpc.ServiceDesc for ExtensionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExtensionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pi.agent.ext.v1.ExtensionService",
	HandlerType: (*ExtensionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initialize",
			Handler:    _ExtensionService_Initialize_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _ExtensionService_Shutdown_Handler,
		},
		{
			MethodName: "OnToolCall",
			Handler:    _ExtensionService_OnToolCall_Handler,
		},
		{
			MethodName: "OnToolResult",
			Handler:    _ExtensionService_OnToolResult_Handler,
		},
		{
			MethodName: "OnContext",
			Handler:    _ExtensionService_OnContext_Handler,
		},
		{
			MethodName: "OnBeforeAgentStart",
			Handler:    _ExtensionService_OnBeforeAgentStart_Handler,
		},
		{
			MethodName: "OnAgentStart",
			Handler:    _ExtensionService_OnAgentStart_Handler,
		},
		{
			MethodName: "OnAgentEnd",
			Handler:    _ExtensionService_OnAgentEnd_Handler,
		},
		{
			MethodName: "OnTurnStart",
			Handler:    _ExtensionService_OnTurnStart_Handler,
		},
		{
			MethodName: "OnTurnEnd",
			Handler:    _ExtensionService_OnTurnEnd_Handler,
		},
		{
			MethodName: "OnSessionStart",
			Handler:    _ExtensionService_OnSessionStart_Handler,
		},
		{
			MethodName: "OnSessionShutdown",
			Handler:    _ExtensionService_OnSessionShutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteTool",
			Handler:       _ExtensionService_ExecuteTool_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "extension.proto",
}

const (
	HostService_SetState_FullMethodName = "/pi.agent.ext.v1.HostService/SetState"
	HostService_Log_FullMethodName      = "/pi.agent.ext.v1.HostService/Log"
)

// HostServiceClient is the client API for HostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostService is implemented by the host process. Extensions can call back
// into the host to update state or emit logs.
type HostServiceClient interface {
	// SetState persists a key-value pair in the extension's state store.
	SetState(ctx context.Context, in *StateSetRequest, opts ...grpc.CallOption) (*Empty, error)
	// Log sends a structured log message to the host.
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Empty, error)
}

type hostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostServiceClient(cc grpc.ClientConnInterface) HostServiceClient {
	return &hostServiceClient{cc}
}

func (c *hostServiceClient) SetState(ctx context.Context, in *StateSetRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostService_SetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostService_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServiceServer is the server API for HostService service.
// All implementations must embed UnimplementedHostServiceServer
// for forward compatibility.
//
// HostService is implemented by the host process. Extensions can call back
// into the host to update state or emit logs.
type HostServiceServer interface {
	// SetState persists a key-value pair in the extension's state store.
	SetState(context.Context, *StateSetRequest) (*Empty, error)
	// Log sends a structured log message to the host.
	Log(context.Context, *LogRequest) (*Empty, error)
	mustEmbedUnimplementedHostServiceServer()
}

// UnimplementedHostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServiceServer struct{}

func (UnimplementedHostServiceServer) SetState(context.Context, *StateSetRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetState not implemented")
}
func (UnimplementedHostServiceServer) Log(context.Context, *LogRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedHostServiceServer) mustEmbedUnimplementedHostServiceServer() {}
func (UnimplementedHostServiceServer) testEmbeddedByValue()                     {}

// UnsafeHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServiceServer will
// result in compilation errors.
type UnsafeHostServiceServer interface {
	mustEmbedUnimplementedHostServiceServer()
}

func RegisterHostServiceServer(s grpc.ServiceRegistrar, srv HostServiceServer) {
	// If the following call panics, it indicates UnimplementedHostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostService_ServiceDesc, srv)
}

func _HostService_SetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).SetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_SetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).SetState(ctx, req.(*StateSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostService_ServiceDesc is the grpc.ServiceDesc for HostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pi.agent.ext.v1.HostService",
	HandlerType: (*HostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetState",
			Handler:    _HostService_SetState_Handler,
		},
		{
			MethodName: "Log",
			Handler:    _HostService_Log_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "extension.proto",
}
